eureka:
  instance:
    prefer-ip-address: 172.30.1.30
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://ec2-3-96-12-133.ca-central-1.compute.amazonaws.com/eureka
