eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://weatherapp-eurekaserver-env-1.eba-eykp88cm.ca-central-1.elasticbeanstalk.com/eureka
